version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    privileged: true
    environment:
      - DOCKER_HOST=unix:///run/docker.sock
    volumes:
      # - ./:/root:z
      - /run/docker.sock:/run/docker.sock:ro
    ports:
      - 80
    networks:
      - backend_net

  load-balancer:
    build:
      context: ./load-balancer
      dockerfile: Dockerfile
    privileged: true
    ports:
      - 80
    depends_on:
      - backend
    networks:
      - backend_net
  
  client_1:
    build:
      context: ./client
      dockerfile: Dockerfile
    privileged: true
    ports: 
      - 80
    networks:
      client_net:
        ipv4_address: 10.0.1.2
    tty: true
    depends_on:
      - router
    
  client_2:
    build:
      context: ./client
      dockerfile: Dockerfile
    privileged: true
    ports: 
      - 80
    networks:
      client_net:
        ipv4_address: 10.0.1.3
    tty: true
    depends_on:
      - router
  
  router:
    build:
      context: ./router
      dockerfile: Dockerfile
    hostname: router
    privileged: true
    networks:
      client_net:
        ipv4_address: 10.0.1.4 # smaller IP range
      backend_net:
        ipv4_address: 10.0.2.6 # smaller IP range
      router_net:
        ipv4_address: 10.0.3.2 # smaller IP range

networks:
  client_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/29
          gateway: 10.0.1.1 # this is used for connectivity to the host

  backend_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/29
          gateway: 10.0.2.1 # this is used for connectivity to the host

  router_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/30
          gateway: 10.0.3.1 # this is used for connectivity to the host
