version: '3'
services:
  external_host:
    build:
      context: ./client
      dockerfile: Dockerfile
    privileged: true
    container_name: external_host
    ports: 
      - 80
    networks:
      public-net:
        ipv4_address: 172.31.255.1
    command: >
      sh -c "/sbin/ip route add 172.16.123.128/28 via 172.31.255.253 && echo 'nameserver 172.31.255.2' > /etc/resolv.conf && /root/sleep.sh"
    tty: true
    depends_on:
      - edge-router

  client-1:
    build:
      context: ./client
    privileged: true
    container_name: client-1
    ports: 
      - 80
    networks:
      client-net-1:
        ipv4_address: 10.0.1.2
    command: >
      sh -c "/sbin/ip route replace default via 10.0.1.254 && echo 'nameserver 10.0.1.3' > /etc/resolv.conf && /root/sleep.sh"
    tty: true
    depends_on:
      - router

  client-2:
    build:
      context: ./client
    privileged: true
    container_name: client-2
    ports: 
      - 80
    networks:
      client-net-2:
        ipv4_address: 10.0.2.2
    command: >
      sh -c "/sbin/ip route replace default via 10.0.2.254 && /root/sleep.sh"
    tty: true
    depends_on:
      - router

  server:
    build:
      context: ./server
    privileged: true
    container_name: server
    ports: 
      - 80
    networks:
      dmz-net:
        ipv4_address: 172.16.123.130
    command: >
      sh -c "/sbin/ip route replace default via 172.16.123.141 && echo 'nameserver 172.16.123.132' > /etc/resolv.conf && /root/sleep.sh"
    tty: true
    depends_on:
      - edge-router

  mail:
    build:
      context: ./server
    privileged: true
    container_name: mail
    ports: 
      - 80
    networks:
      dmz-net:
        ipv4_address: 172.16.123.131
    command: >
      sh -c "/sbin/ip route replace default via 172.16.123.141 && echo 'nameserver 172.16.123.132' > /etc/resolv.conf && /root/sleep.sh"
    tty: true
    depends_on:
      - edge-router

  dns-internal-cache:
    build:
      context: ./dns-cache
    privileged: true
    container_name: dns-internal-cache
    ports: 
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      client-net-1:
        ipv4_address: 10.0.1.3
    tty: true
    command: >
      sh -c "/sbin/ip route replace default via 10.0.1.254 && service named start && /root/sleep.sh"
    volumes:
      - "./dns-cache/internal/cache:/var/cache/bind"
      - "./dns-cache/internal/records:/var/lib/bind"
      # - "./dns-cache/internal/config/db.myorg.net:/etc/bind/db.myorg.net"
      # - "./dns-cache/internal/config/db.internal.myorg.net:/etc/bind/db.internal.myorg.net"
      # - "./dns-cache/internal/config/named.conf.local:/etc/bind/named.conf.local"
      - "./dns-cache/internal/config/named.conf.options:/etc/bind/named.conf.options"
    depends_on:
      - edge-router
      - dns-server

  dns-external-cache:
    build:
      context: ./dns-cache
    privileged: true
    container_name: dns-external-cache
    ports: 
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      public-net:
        ipv4_address: 172.31.255.2
    tty: true
    command: >
      sh -c "/sbin/ip route replace default via 172.31.255. && service named start && /root/sleep.sh"
    volumes:

      - "./dns-cache/external/cache:/var/cache/bind"
      - "./dns-cache/external/records:/var/lib/bind"
      # - "./dns-cache/external/config/db.myorg.net:/etc/bind/db.myorg.net"
      # - "./dns-cache/external/config/db.internal.myorg.net:/etc/bind/db.internal.myorg.net"
      # - "./dns-cache/external/config/named.conf.local:/etc/bind/named.conf.local"
      - "./dns-cache/external/config/named.conf.options:/etc/bind/named.conf.options"
    depends_on:
      - edge-router
      - dns-server

  dns:
    build:
      context: ./dns-server
    privileged: true
    container_name: dns
    ports: 
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      dmz-net:
        ipv4_address: 172.16.123.132
    tty: true
    command: >
      sh -c "/sbin/ip route replace default via 172.16.123.141 && service named start && /root/sleep.sh"
    volumes:
      - "./dns-server/cache:/var/cache/bind"
      - "./dns-server/records:/var/lib/bind"
      - "./dns-server/config/db.myorg.net:/etc/bind/db.myorg.net"
      - "./dns-server/config/db.internal.myorg.net:/etc/bind/db.internal.myorg.net"
      - "./dns-server/config/named.conf.local:/etc/bind/named.conf.local"
      - "./dns-server/config/named.conf.options:/etc/bind/named.conf.options"
    depends_on:
      - edge-router

  router:
    build:
      context: ./router
    container_name: router
    privileged: true
    networks:
      client-net-1:
        ipv4_address: 10.0.1.254
      client-net-2:
        ipv4_address: 10.0.2.254
      dmz-net:
        ipv4_address: 172.16.123.142

  edge-router:
    build:
      context: ./edge-router
    container_name: edge-router
    privileged: true
    networks:
      dmz-net:
        ipv4_address: 172.16.123.141
      public-net:
        ipv4_address: 172.31.255.253

networks:
  client-net-1:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
           
  client-net-2:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.1

  dmz-net:
      ipam:
        driver: default
        config:
          - subnet: 172.16.123.128/28
            gateway: 172.16.123.129

  public-net:
      ipam:
        driver: default
        config:
          - subnet: 172.31.255.0/24
            gateway: 172.31.255.254